version: '3.8'

services:
  backend:
    build: ./back
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./front
    ports:
      - "8501:8501"
    restart: always
    depends_on:
      - backend