version: '3.8'

services:
  back:
    build: ./back
    container_name: recommend-back
    ports:
      - "8000:8000"
    volumes:
      - ./recommend.json:/app/recommend.json
    restart: always

  front:
    build: ./front
    container_name: recommend-front
    ports:
      - "80:8501"
    volumes:
      - ./recommend.json:/app/recommend.json
    restart: always
    depends_on:
      - back